# Generated by Django 3.1.5 on 2021-10-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazilarmodel',
            name='duzenlenme_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
